name: AoC 2024 Solutions
on:
  workflow_dispatch:
    inputs:
      day:
        description: 'Day to execute (leave empty to execute all days)'
        required: false
        default: ''
      part:
        description: 'The part of the day to execute (either "1" or "2" or just leave empty to execute both parts). Will be ignored if the day is not set.'
        required: false
        default: ''

jobs:
  solve:
    name: Solve Puzzles
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: stable
          swi-prolog-version: latest
      - name: Checkout AoC
        uses: actions/checkout@v1
      - name: Solve
        run: if [ -z "${{ github.event.inputs.day }}" ]; then ./solveAll.sh; else ./solveAll.sh "${{ github.event.inputs.day }}" "${{ github.event.inputs.part }}"; fi
